source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PKHUDObjC_Example', :exclusive => true do
  pod "PKHUDObjC", :path => "../"
end

target 'PKHUDObjC_Tests', :exclusive => true do
  pod "PKHUDObjC", :path => "../"

  
end
